name: Vercel Preview URL

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  deployments: write
  statuses: write
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Preview
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: false
